# -*- coding: utf-8 -*-
"""Password_checker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nUPoIX8noGLq55IERGAXPfWSMSQkF0zl
"""

import re

def check_password_strength(password):
    length_error = len(password) < 8
    lowercase_error = re.search(r"[a-z]", password) is None
    uppercase_error = re.search(r"[A-Z]", password) is None
    digit_error = re.search(r"\d", password) is None
    special_char_error = re.search(r"[@#$%^&+=!]", password) is None

    errors = [length_error, lowercase_error, uppercase_error, digit_error, special_char_error]
    error_count = sum(errors)

    if error_count == 0:
        strength = "🔒 Strong password"
    elif error_count <= 2:
        strength = "🔐 Medium password"
    else:
        strength = "⚠️ Weak password"

    return strength

# Input from user
password = input("Enter your password: ")
result = check_password_strength(password)
print("Result:", result)

